---
services:

  script:
    platform: 'linux/amd64'
    build:
      context: .
    env_file:
      - path: ./.env
        required: true
      - path: ./.sentry
        required: false
    volumes:
      - ./logs:/tmp/logs
    restart: always
